import { IntegrationId } from "@bitwarden/common/tools/integration";

import { CategorizedAlgorithm, Category } from "./data";

/** A collection of credentials that all fulfill a specific purpose. */
export type CredentialCategory = keyof typeof Category;

/** A type of password that may be generated by the credential generator. */
export type PasswordAlgorithm = (typeof CategorizedAlgorithm.password)[number];

/** A type of username that may be generated by the credential generator. */
export type UsernameAlgorithm = (typeof CategorizedAlgorithm.username)[number];

/** A type of email address that may be generated by the credential generator. */
export type EmailAlgorithm = (typeof CategorizedAlgorithm.email)[number] | ForwarderIntegration;

/** Identifies a forwarding service */
export type ForwarderIntegration = { forwarder: IntegrationId };

/** A type of credential that may be generated by the credential generator. */
// this is defined in terms of `CategorizedAlgorithm` to typecheck the keys of
// `CredentialCategory` against the keys of `Category`.
export type CredentialAlgorithm =
  | (typeof CategorizedAlgorithm)[CredentialCategory][number]
  | ForwarderIntegration;
